### ISSUE TITLE
Problem: Exception while invoking method 'addSocialResource'

### ISSUE THREAD

**Issue by ryankingtm** [EmurgoHK/cardanoupdate#805]
problem: When adding a new community (https://cardanoupdate.space/community) there's a server side exception:
Exception while invoking method 'addSocialResource' ( _id is not defined ). This is the line where the exception happens: https://github.com/EmurgoHK/cardanoupdate/blob/1e613c21686398debf262742cdd17c7d9a24228b/imports/api/socialResources/methods.js#L129

```
Exception while invoking method 'addSocialResource' { stack:
   'ReferenceError: _id is not defined\n    at MethodInvocation.run (imports/api/socialResources/methods.js:127:88)\n    at ValidatedMethod._execute (packages/mdg:validated-method/validated-method.js:93:12)\n    at MethodInvocation.addSocialResource (packages/mdg:validated-method/validated-method.js:54:23)\n    at MethodInvocation.methodMap.(anonymous function) (packages/meteorhacks_kadira.js:2731:30)\n    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1767:12)\n    at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:719:19)\n    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1189:12)\n    at DDPServer._CurrentWriteFence.withValue (packages/ddp-server/livedata_server.js:717:46)\n    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1189:12)\n    at Promise (packages/ddp-server/livedata_server.js:715:46)\n    at new Promise (<anonymous>)\n    at Session.method (packages/ddp-server/livedata_server.js:689:23)\n    at packages/meteorhacks_kadira.js:2619:38\n    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1189:12)\n    at Session.sessionProto.protocol_handlers.method (packages/meteorhacks_kadira.js:2618:44)\n    at packages/ddp-server/livedata_server.js:559:43',
  source: 'method' }
```

**Comment by ryankingtm** [comment]
Note, I haven't received my verification email yet, so I am submitting as an unverified user.
